### ISSUE TITLE
ValueError: Error when checking input: expected input_14 to have shape (None, 1850) but got array with shape (1480, 1)

### ISSUE THREAD

**Issue by simarad** [bhaveshoswal/CNN-text-classification-keras#1]
Hi,
I used you helper code to prepare my dataset and then run the model. i have:
X_train=(1480,0)
y_train = (850,0)
X_test = (370,0)
y_test = (370,0)
sequence_length = 1850
the rest of parameters are the same, when i run the model, i got the error:ValueError: Error when checking input: expected input_14 to have shape (None, 1850) but got array with shape (1480, 1).

sorry, i am new, what should i do?
thanks,

**Comment by bhaveshoswal** [comment]
for sequence_length=1850, you should have X_train shape = (1480,1850)
can you give me the dataset.
