### ISSUE TITLE
How to cite it?

### ISSUE THREAD

**Issue by amali** [bhaveshoswal/CNN-text-classification-keras#2]
Very easy to use, thanks! Any idea how to cite this implementation?

**Comment by bhaveshoswal** [comment]
@misc{bhaveshoswal, author = {Bhavesh Vinod Oswal}, title = {CNN-text-classification-keras}, year = {2016}, publisher = {GitHub}, journal = {GitHub repository}, howpublished = {\url{https://github.com/bhaveshoswal/CNN-text-classification-keras}}, }
